### ISSUE TITLE
"Step through" animations

### ISSUE THREAD

**Issue by slimsag** [dai-shi/excalidraw-animate#8]
I'd love to use this in order to teach concepts and do a voice-over recording while the animation plays - similar to drawing on a whiteboard while recording.

One challenge with that today, is that I need to hit the play/pause key at the exact right time (otherwise it pauses when the animation is half way finished).

I really wish there was a way to step through the animations, like using the left and right keys to play the next part of the animation or go back to the previous step in the animation.

**Comment by dai-shi** [comment]
Because of what it's using (svg animation tag), it's technically difficult to stop on each animation.
Hm, but we know the length, it might be possible. Let me try.
(The secret is 0.5 sec for a single shape and 5 sec for a group of shapes.)

This is not an authoring tool, and the use case I have in mind is record it and edit it as video.
Someone made a nice one: https://www.youtube.com/watch?v=9jvMiq4CZJ0

**Comment by dai-shi** [comment]
> it might be possible. Let me try.

it wasn't easy. now trying another (possibly better) way.
